stages:
  - setup

cache:
  paths:
    - tests/roles
    - var

setup:
  stage: setup
  tags: [docker]
  script:
    - ./tests/ops/bin/ansible ansible-galaxy install -r ./tests/requirements.yml --roles-path ./tests/roles/
    - ./tests/ops/bin/ansible ansible-playbook tests/test.yml