stages:
  - setup_runner

cache:
  paths:
    - roles
    - tmp

setup:
  stage: setup_runner
  tags: [docker]
  after_script:
    - docker run --rm -v `pwd`:/mnt busybox chown -R `id -u` /mnt/
  script:
    - echo "$SSH_PRIVATE_KEY" > id_rsa
    # - docker run --rm -w /var/www -v `pwd`:/var/www -v `pwd`/id_rsa:/root/.ssh/id_rsa:ro lexauw/ansible-alpine ansible-galaxy -r requirements.yml install
    - docker run --rm -w /var/www -v `pwd`:/var/www -v `pwd`/id_rsa:/root/.ssh/id_rsa:ro lexauw/ansible-alpine ansible-playbook playbook.yml
