- name: Prepare directories for shared folders
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{nginx.dir}}/mnt/etc/nginx/conf.d"
    - "{{nginx.dir}}/mnt/etc/nginx/ssl"
    - "{{nginx.dir}}/mnt/var/log/nginx"
    - "{{nginx.dir}}/mnt/var/www/html"

- name: Check dhparam key
  stat:
    path: "{{nginx.dir}}/mnt/etc/nginx/ssl/dhparam.pem"
  register: dhparam

- name: Diffie-Hellman parameter for DHE ciphersuites
  shell: "openssl dhparam -out {{nginx.dir}}/mnt/etc/nginx/ssl/dhparam.pem {{nginx.openssl_dhparam_numbits}}"
  when: dhparam.stat.exists == false

- name: Setup nginx configs
  register: config
  template:
    src: "templates/etc/nginx/{{item}}"
    dest: "{{nginx.dir}}/mnt/etc/nginx/{{item}}"
  with_items:
    - conf.d/htpasswd
    - conf.d/restricted
    - nginx.conf
  notify:
    - Restart nginx

- name: Run nginx server
  register: nginx
  docker_container:
    image: "nginx:alpine"
    name: "nginx"
    pull: yes
    state: started
    user: root
    ports:
      - "{{nginx.container.ports.https}}:443"
      - "{{nginx.container.ports.http}}:80"
    volumes: "{{nginx.container.volumes}} + [
        '{{nginx.dir}}/mnt/etc/nginx/conf.d:/etc/nginx/conf.d:ro',
        '{{nginx.dir}}/mnt/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro',
        '{{nginx.dir}}/mnt/etc/nginx/ssl:/etc/nginx/ssl:ro',
        '{{nginx.dir}}/mnt/var/log/nginx:/var/log/nginx',
        '{{nginx.dir}}/mnt/var/www/html:/var/www/html'
      ]"
  when: ansible_facts.virtualization_type != "docker"

- meta: flush_handlers