- name: Prepare directories for shared folders
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{nginx.dir}}/etc/nginx/conf.d"
    - "{{nginx.dir}}/etc/nginx/ssl"
    - "{{nginx.dir}}/var/log/nginx"
    - "{{nginx.dir}}/var/www/html"

- name: Check dhparam key
  stat:
    path: "{{nginx.dir}}/etc/nginx/ssl/dhparam.pem"
  register: dhparam

- name: Diffie-Hellman parameter for DHE ciphersuites
  shell: "openssl dhparam -out {{nginx.dir}}/etc/nginx/ssl/dhparam.pem {{nginx.openssl_dhparam_numbits}}"
  when: dhparam.stat.exists == false

- name: Setup nginx configs
  register: config
  template:
    src: "templates/etc/nginx/{{item}}"
    dest: "{{nginx.dir}}/etc/nginx/{{item}}"
  with_items:
    - conf.d/htpasswd
    - conf.d/restricted
    - nginx.conf
  notify:
    - Restart nginx

- name: Run nginx server
  register: nginx
  docker_container:
    image: "{{nginx.container.image}}"
    name: "{{nginx.container_name}}"
    pull: yes
    state: started
    user: root
    log_driver: "{{nginx.container.log_driver}}"
    log_options: "{{nginx.container.log_options}}"
    ports: "{{nginx.container.ports}}"
    expose: '{{nginx.container.expose}}'
    volumes: "{{nginx.container.volumes}} + [
        '{{nginx.dir}}/etc/nginx/conf.d:/etc/nginx/conf.d:ro',
        '{{nginx.dir}}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro',
        '{{nginx.dir}}/etc/nginx/ssl:/etc/nginx/ssl:ro',
        '{{nginx.dir}}/var/log/nginx:/var/log/nginx',
        '{{nginx.dir}}/var/www/html:/var/www/html:ro'
      ]"
  when: ansible_facts.virtualization_type != "docker"

- meta: flush_handlers